#!/bin/bash
set -e

echo "Starting Phase C: PR Creator..."

JSON_FILE="analysis_result.json"

if [ ! -f "$JSON_FILE" ]; then
    echo "Error: $JSON_FILE not found. Analysis phase might have failed."
    exit 1
fi

# Extract values using Python since jq might not be available on all runners
ROOT_CAUSE=$(python3 -c "import json; print(json.load(open('$JSON_FILE'))['root_cause'])")
FILE_TO_FIX=$(python3 -c "import json; print(json.load(open('$JSON_FILE'))['file_to_fix'])")

echo "Root cause identified: $ROOT_CAUSE"
echo "Target file: $FILE_TO_FIX"

# Run a python script to perform the search and replace
cat << 'EOF' > string_replace.py
import json
import sys
import os

with open("analysis_result.json", "r") as f:
    data = json.load(f)

file_to_fix = data.get("file_to_fix")
search_content = data.get("search_content", "")
replace_content = data.get("replace_content", "")

# Sanitize the filepath (LLMs sometimes add leading ./ or the repo name)
if file_to_fix.startswith("./"):
    file_to_fix = file_to_fix[2:]
if file_to_fix.startswith("CI-CD-AI-Agent/"):
    file_to_fix = file_to_fix.replace("CI-CD-AI-Agent/", "", 1)
if not os.path.exists(file_to_fix):
    # Try to find it dynamically by basename if the long path is wrong
    basename = os.path.basename(file_to_fix)
    for root, dirs, files in os.walk("."):
        if basename in files:
            file_to_fix = os.path.join(root, basename)
            break

if not search_content:
    print("Warning: No search_content provided by AI. Cannot create a PR automatically.")
    sys.exit(0)

try:
    with open(file_to_fix, "r") as f:
        content = f.read()

    if search_content not in content:
        print(f"Failed to apply patch. The AI suggested search string was not found in {file_to_fix}.")
        print(f"Search string:\n{search_content}")
        sys.exit(1)

    new_content = content.replace(search_content, replace_content)

    with open(file_to_fix, "w") as f:
        f.write(new_content)
    
    print("Code replaced successfully!")
except Exception as e:
    print(f"Error modifying file: {e}")
    sys.exit(1)
EOF

# Prepare branch
BRANCH_NAME="fix/build-${GITHUB_RUN_ID}"
echo "Checking out new branch: $BRANCH_NAME"
git checkout -b "$BRANCH_NAME" || git checkout "$BRANCH_NAME"

# Apply the replaced content
echo "Applying code changes..."
python3 string_replace.py

# Commit and Push
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"

git add "$FILE_TO_FIX"
git commit -m "🤖 AI suggested fix for build failure"

echo "Pushing changes to origin..."
git push origin "$BRANCH_NAME"

# Create PR via GH CLI
echo "Creating Pull Request..."
PR_BODY="## AI Analysis 🤖

**Root Cause:**
$ROOT_CAUSE

This PR was automatically generated by the CI Healer Action for Run ID: $GITHUB_RUN_ID."

gh pr create \
    --title "Fix: Build Failure in Run $GITHUB_RUN_ID" \
    --body "$PR_BODY" \
    --head "$BRANCH_NAME" \
    --base main

echo "PR created successfully!"
