#!/bin/bash
set -e

echo "Starting Phase C: PR Creator..."

JSON_FILE="analysis_result.json"

if [ ! -f "$JSON_FILE" ]; then
    echo "Error: $JSON_FILE not found. Analysis phase might have failed."
    exit 1
fi

# Extract values using Python since jq might not be available on all runners
ROOT_CAUSE=$(python3 -c "import json; print(json.load(open('$JSON_FILE'))['root_cause'])")
FILE_TO_FIX=$(python3 -c "import json; print(json.load(open('$JSON_FILE'))['file_to_fix'])")
DIFF_PATCH=$(python3 -c "import json; print(json.load(open('$JSON_FILE'))['diff_patch'])")

echo "Root cause identified: $ROOT_CAUSE"
echo "Target file: $FILE_TO_FIX"

if [ -z "$DIFF_PATCH" ]; then
    echo "Warning: No diff patch provided by AI. Cannot create a PR automatically."
    exit 0
fi

# Save the diff to a patch file
PATCH_FILE="fix.patch"
echo "$DIFF_PATCH" > "$PATCH_FILE"

# Prepare branch
BRANCH_NAME="fix/build-${GITHUB_RUN_ID}"
echo "Checking out new branch: $BRANCH_NAME"
git checkout -b "$BRANCH_NAME" || git checkout "$BRANCH_NAME"

# Apply the patch
echo "Applying patch..."
if git apply "$PATCH_FILE"; then
    echo "Patch applied successfully!"
else
    echo "Failed to apply patch. The AI suggested an invalid or conflicting diff."
    # Output the patch for debugging
    cat "$PATCH_FILE"
    exit 1
fi

# Commit and Push
git config user.name "github-actions[bot]"
git config user.email "github-actions[bot]@users.noreply.github.com"

git add "$FILE_TO_FIX"
git commit -m "🤖 AI suggested fix for build failure"

echo "Pushing changes to origin..."
git push origin "$BRANCH_NAME"

# Create PR via GH CLI
echo "Creating Pull Request..."
PR_BODY="## AI Analysis 🤖

**Root Cause:**
$ROOT_CAUSE

This PR was automatically generated by the CI Healer Action for Run ID: $GITHUB_RUN_ID."

gh pr create \
    --title "Fix: Build Failure in Run $GITHUB_RUN_ID" \
    --body "$PR_BODY" \
    --head "$BRANCH_NAME" \
    --base main

echo "PR created successfully!"
